// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Author': string;
  'Body': string;
  'Comment': string;
}
declare var cssExports: CssExports;
export = cssExports;
