// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FormContainer': string;
  'SubmissionError': string;
}
declare var cssExports: CssExports;
export = cssExports;
