// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Error': string;
  'Field': string;
  'HasError': string;
  'TypeLine': string;
}
declare var cssExports: CssExports;
export = cssExports;
