// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ErrorCode': string;
  'ErrorContainer': string;
  'ErrorMessage': string;
}
declare var cssExports: CssExports;
export = cssExports;
