// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Loader': string;
  'Loader1': string;
  'Loader2': string;
  'Loader3': string;
}
declare var cssExports: CssExports;
export = cssExports;
